SOURCE_CONFIGS = [
    {
        'source_name': 'careerviet',
        'title': 'h2 a.job_link@text()',
        'company': 'a.company-name@text()',
        'company_location': 'div.location ul li@text()',
        'location_working_type': None,
        'working_type': None,
        'date_posted': 'div.time ul li time@text()',
        'number_applicants': None,
        'prefix_job_url': 'https://careerviet.vn',
        'job_url': 'a.job_link@href',
        'description': None,
        'salary': 'div.salary p@text()',
        'role': None,
        'level': None,
    },
    # {
    #     'source_name': 'joboko',
    #     'title': 'h2.item-title a@text()',
    #     'company': 'div.item-info div.item-company span@text()',
    #     'company_location': 'div.item-info div.item-address span@text()',
    #     'location_working_type': None,
    #     'working_type': None,
    #     'date_posted': 'div.item-new-footer div.item-date-v2 span.item-date@data-value',
    #     'number_applicants': None,
    #     'prefix_job_url': 'https://vn.joboko.com',
    #     'job_url': 'h2.item-title a@href',
    #     'description': 'div.fz-13.item-text ul li@text()',
    #     'salary': 'div.item-info div.item-rate span@text()',
    #     'role': None,
    #     'level': None,
    # },
    # {
    #     'source_name': 'careerlink',
    #     'title': 'h5.job-name@text()',
    #     'company': 'a.job-company@text()',
    #     'company_location': 'div.job-location a@text()',
    #     'location_working_type': None,
    #     'working_type': 'a.job-position@text()',
    #     'date_posted': 'span.job-update-time span.cl-datetime@data-datetime',
    #     'number_applicants': None,
    #     'prefix_job_url': 'https://www.careerlink.vn',
    #     'job_url': 'a.job-link@href',
    #     'description': None,
    #     'salary': 'span.job-salary@text()',
    #     'role': None,
    #     'level': 'a.job-position@text()',
    # },
    # {
    #     'source_name': 'topdev',
    #     'title': 'a[href^="/viec-lam/"]@text()',
    #     'company': 'a[href^="/viec-lam/"] + span@text()',
    #     'company_location': None,
    #     'location_working_type': None,
    #     'working_type': None,
    #     'date_posted': None,
    #     'number_applicants': None,
    #     'prefix_job_url': 'https://topdev.vn',
    #     'job_url': 'a[href^="/viec-lam/"]@href',
    #     'description': None,
    #     'salary': 'span.cursor-pointer@text()',
    #     'role': 'a[href*="/jobs/search"]@text()',
    #     'level': None,
    # },
]
