SOURCE_CONFIGS = [{'source_name': 'careerviet',
  'title': 'h2 a.job_link@text()',
  'company': 'a.company-name@text()',
  'company_location': 'div.location ul li@text()',
  'location_working_type': None,
  'working_type': None,
  'date_posted': 'div.time ul li time@text()',
  'number_applicants': None,
  'prefix_job_url': 'https://careerviet.vn',
  'job_url': 'a.job_link@href',
  'description': None,
  'salary': 'div.salary p@text()',
  'role': None,
  'level': None}]
